server:
  port: ${SERVER_PORT:18082}

spring:
  application:
    name: preference-service
  kafka:
    consumer:
      group-id: preference-service-group

grpc:
  server:
    port: ${GRPC_SERVER_PORT:19092}
