server:
  port: ${SERVER_PORT:18081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:19091}

pcm:
  profile:
    cache:
      ttl: 300
    events:
      topic: profile-events
    vault:
      transit:
        enabled: true
        key-name: pcm-pii-key
