server:
  port: ${SERVER_PORT:18084}

spring:
  application:
    name: segment-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
  kafka:
    consumer:
      group-id: segment-service-group
  cloud:
    function:
      definition: profileCreated;profileUpdated

grpc:
  server:
    port: ${GRPC_SERVER_PORT:19094}
