apiVersion: v2
name: pcm
description: A privacy-first identity and consent management platform
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 22.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: elasticsearch
    version: 19.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
