apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: pcm
data:
  PROFILE_SERVICE_URL: "http://profile-service:8081"
  CONSENT_SERVICE_URL: "http://consent-service:8082"
  SEGMENT_SERVICE_URL: "http://segment-service:8083"
  PREFERENCE_SERVICE_URL: "http://preference-service:8084"
  REDIS_HOST: "redis-master"
  PROFILE_GRPC_HOST: "profile-service"
  PROFILE_GRPC_PORT: "9091"
  SEGMENT_GRPC_HOST: "segment-service"
  SEGMENT_GRPC_PORT: "9093"
  PREFERENCE_GRPC_HOST: "preference-service"
  PREFERENCE_GRPC_PORT: "9094"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: pcm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: pcm/api-gateway:0.1.0-SNAPSHOT
        ports:
        - containerPort: 9880
          name: http
        envFrom:
        - configMapRef:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: pcm
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 9880
  type: LoadBalancer
