apiVersion: v1
kind: ConfigMap
metadata:
  name: preference-service-config
  namespace: pcm
data:
  SPRING_DATA_REDIS_HOST: "redis-master"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preference-service
  namespace: pcm
  labels:
    app: preference-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preference-service
  template:
    metadata:
      labels:
        app: preference-service
    spec:
      containers:
      - name: preference-service
        image: pcm/preference-service:0.1.0-SNAPSHOT
        ports:
        - containerPort: 8084
          name: http
        - containerPort: 9094
          name: grpc
        envFrom:
        - configMapRef:
            name: preference-service-config
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: preference-service
  namespace: pcm
spec:
  selector:
    app: preference-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: grpc
    port: 9094
    targetPort: 9094
  type: ClusterIP
