apiVersion: v1
kind: ConfigMap
metadata:
  name: segment-service-config
  namespace: pcm
data:
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch-master:9200"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  PCM_TOPICS_PROFILE_EVENTS: "profile-events"
  PCM_TOPICS_SEGMENT_EVENTS: "segment-events"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: segment-service
  namespace: pcm
  labels:
    app: segment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segment-service
  template:
    metadata:
      labels:
        app: segment-service
    spec:
      containers:
      - name: segment-service
        image: pcm/segment-service:0.1.0-SNAPSHOT
        ports:
        - containerPort: 8083
          name: http
        - containerPort: 9093
          name: grpc
        envFrom:
        - configMapRef:
            name: segment-service-config
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: segment-service
  namespace: pcm
spec:
  selector:
    app: segment-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: grpc
    port: 9093
    targetPort: 9093
  type: ClusterIP
